export const styles = {
    root: {
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
      minHeight: '100vh',
      background: '#1c1c1c',
      fontFamily:
        "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Segoe UI', sans-serif",
      color: '#fff',
    },
  
    leftPanel: {
      background: '#161616',
      borderRight: '1px solid rgba(255,255,255,0.07)',
      display: 'flex',
      flexDirection: 'column',
      padding: '28px 40px 32px',
    },
    brand: {
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
      textDecoration: 'none',
      marginBottom: '0',
    },
    brandDot: {
      width: '10px',
      height: '10px',
      borderRadius: '50%',
      background: '#3b82f6',
    },
    brandText: {
      fontWeight: 600,
      fontSize: '15px',
      color: '#fff',
      letterSpacing: '-0.01em',
    },
    leftContent: {
      flex: 1,
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      paddingBottom: '24px',
    },
    leftEyebrow: {
      fontSize: '12px',
      fontWeight: 500,
      color: '#3b82f6',
      letterSpacing: '0.08em',
      textTransform: 'uppercase',
      marginBottom: '12px',
    },
    leftHeading: {
      fontSize: 'clamp(26px, 2.8vw, 36px)',
      fontWeight: 700,
      lineHeight: 1.15,
      letterSpacing: '-0.02em',
      color: '#fff',
      marginBottom: '14px',
    },
    leftSub: {
      fontSize: '14px',
      color: 'rgba(255,255,255,0.4)',
      lineHeight: 1.65,
      maxWidth: '340px',
      marginBottom: '28px',
    },
  
    codeBlock: {
      background: '#0f0f0f',
      border: '1px solid rgba(255,255,255,0.08)',
      borderRadius: '12px',
      overflow: 'hidden',
    },
    codeTopBar: {
      display: 'flex',
      alignItems: 'center',
      gap: '10px',
      padding: '9px 14px',
      background: '#1a1a1a',
      borderBottom: '1px solid rgba(255,255,255,0.06)',
    },
    codeDots: { display: 'flex', gap: '5px' },
    codeDot: { width: '9px', height: '9px', borderRadius: '50%' },
    codeFileName: {
      fontSize: '11px',
      color: 'rgba(255,255,255,0.3)',
      fontFamily: "'JetBrains Mono','Fira Code',monospace",
      marginLeft: '2px',
    },
    codeBody: {
      padding: '14px 0',
      fontFamily: "'JetBrains Mono','Fira Code','Courier New',monospace",
      fontSize: '12px',
      lineHeight: 1.75,
      minHeight: '180px',
    },
    codeLine: {
      display: 'flex',
      alignItems: 'flex-start',
      padding: '0 14px',
    },
    codeNum: {
      minWidth: '28px',
      color: 'rgba(255,255,255,0.15)',
      userSelect: 'none',
      flexShrink: 0,
      textAlign: 'right',
      marginRight: '12px',
    },
    cursor: {
      display: 'inline-block',
      width: '2px',
      height: '13px',
      background: '#3b82f6',
      verticalAlign: 'text-bottom',
      marginLeft: '1px',
      animation: 'blink 1s infinite',
    },
  
    leftStats: {
      display: 'flex',
      gap: '0',
      borderTop: '1px solid rgba(255,255,255,0.07)',
      paddingTop: '20px',
    },
    stat: {
      flex: 1,
      display: 'flex',
      flexDirection: 'column',
      gap: '3px',
      paddingRight: '20px',
    },
    statNum: {
      fontSize: '18px',
      fontWeight: 700,
      color: '#fff',
      letterSpacing: '-0.02em',
    },
    statLabel: { fontSize: '11px', color: 'rgba(255,255,255,0.35)' },
  
    rightPanel: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '40px 32px',
    },
    formCard: {
      width: '100%',
      maxWidth: '400px',
    },
    formHeader: { marginBottom: '28px' },
    formTitle: {
      fontSize: '26px',
      fontWeight: 700,
      letterSpacing: '-0.02em',
      color: '#fff',
      marginBottom: '6px',
    },
    formSubtitle: {
      fontSize: '14px',
      color: 'rgba(255,255,255,0.4)',
    },
    authLink: {
      color: '#3b82f6',
      textDecoration: 'none',
      fontWeight: 500,
      transition: 'color 0.15s',
    },
    forgotLink: {
      fontSize: '12px',
      color: 'rgba(255,255,255,0.35)',
      textDecoration: 'none',
      transition: 'color 0.15s',
    },
  
    errorBox: {
      display: 'flex',
      alignItems: 'flex-start',
      gap: '8px',
      background: 'rgba(239,68,68,0.08)',
      border: '1px solid rgba(239,68,68,0.2)',
      borderRadius: '8px',
      padding: '10px 14px',
      fontSize: '13px',
      color: '#f87171',
      marginBottom: '20px',
      lineHeight: 1.5,
    },
  
    form: { display: 'flex', flexDirection: 'column', gap: '18px' },
    fieldGroup: { display: 'flex', flexDirection: 'column', gap: '7px' },
    label: {
      fontSize: '13px',
      fontWeight: 500,
      color: 'rgba(255,255,255,0.7)',
    },
    inputWrap: {
      display: 'flex',
      alignItems: 'center',
      gap: '10px',
      background: 'rgba(255,255,255,0.04)',
      border: '1px solid',
      borderRadius: '10px',
      padding: '0 14px',
      height: '44px',
      transition: 'border-color 0.2s, box-shadow 0.2s',
    },
    input: {
      flex: 1,
      background: 'transparent',
      border: 'none',
      outline: 'none',
      color: '#fff',
      fontSize: '14px',
      fontFamily: 'inherit',
      caretColor: '#3b82f6',
    },
    eyeBtn: {
      background: 'none',
      border: 'none',
      cursor: 'pointer',
      padding: '2px',
      display: 'flex',
      alignItems: 'center',
      flexShrink: 0,
    },
  
    submitBtn: {
      height: '44px',
      borderRadius: '10px',
      background: 'rgba(255,255,255,0.09)',
      border: '1px solid rgba(255,255,255,0.18)',
      color: '#fff',
      fontSize: '14px',
      fontWeight: 600,
      cursor: 'pointer',
      transition: 'background 0.15s, transform 0.15s, opacity 0.15s',
      letterSpacing: '-0.01em',
    },
    spinner: {
      width: '14px',
      height: '14px',
      border: '2px solid rgba(255,255,255,0.2)',
      borderTop: '2px solid #fff',
      borderRadius: '50%',
      animation: 'spin 0.7s linear infinite',
      display: 'inline-block',
    },
  
    divider: {
      display: 'flex',
      alignItems: 'center',
      gap: '12px',
      margin: '22px 0',
    },
    dividerLine: {
      flex: 1,
      height: '1px',
      background: 'rgba(255,255,255,0.08)',
    },
    dividerText: {
      fontSize: '12px',
      color: 'rgba(255,255,255,0.3)',
      whiteSpace: 'nowrap',
    },
  
    githubBtn: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '10px',
      width: '100%',
      height: '44px',
      borderRadius: '10px',
      background: 'rgba(255,255,255,0.04)',
      border: '1px solid rgba(255,255,255,0.12)',
      color: 'rgba(255,255,255,0.75)',
      fontSize: '14px',
      fontWeight: 500,
      cursor: 'pointer',
      transition: 'background 0.15s',
    },
  
    footerNote: {
      marginTop: '20px',
      fontSize: '12px',
      color: 'rgba(255,255,255,0.25)',
      textAlign: 'center',
      lineHeight: 1.6,
    },
    termsLink: {
      color: 'rgba(255,255,255,0.45)',
      textDecoration: 'underline',
      textDecorationColor: 'rgba(255,255,255,0.2)',
    },
  };