export const S = {
    root: {
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
      minHeight: '100vh',
      background: '#1c1c1c',
      fontFamily:
        "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Segoe UI', sans-serif",
      color: '#fff',
    },
  
    left: {
      background: '#161616',
      borderRight: '1px solid rgba(255,255,255,0.07)',
      display: 'flex',
      flexDirection: 'column',
      padding: '28px 40px 32px',
    },
    brand: {
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
      textDecoration: 'none',
    },
    brandDot: {
      width: '10px',
      height: '10px',
      borderRadius: '50%',
      background: '#3b82f6',
    },
    brandText: {
      fontWeight: 600,
      fontSize: '15px',
      color: '#fff',
      letterSpacing: '-0.01em',
    },
    leftBody: {
      flex: 1,
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      paddingBottom: '20px',
    },
    eyebrow: {
      fontSize: '12px',
      fontWeight: 500,
      color: '#1D9E75',
      letterSpacing: '0.08em',
      textTransform: 'uppercase',
      marginBottom: '12px',
      margin: '0 0 12px',
    },
    heading: {
      fontSize: 'clamp(26px, 2.8vw, 36px)',
      fontWeight: 700,
      lineHeight: 1.15,
      letterSpacing: '-0.02em',
      color: '#fff',
      marginBottom: '14px',
    },
    accent: {
      background: 'linear-gradient(90deg, #3b82f6, #1D9E75)',
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent',
    },
    sub: {
      fontSize: '14px',
      color: 'rgba(255,255,255,0.4)',
      lineHeight: 1.65,
      maxWidth: '340px',
      marginBottom: '28px',
      margin: '0 0 28px',
    },
    featureItem: {
      display: 'flex',
      alignItems: 'flex-start',
      gap: '12px',
      padding: '11px 13px',
      borderRadius: '10px',
      border: '1px solid',
    },
    featureIconBox: {
      width: '28px',
      height: '28px',
      borderRadius: '7px',
      background: 'rgba(255,255,255,0.06)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
      marginTop: '1px',
    },
    featureTitle: {
      fontSize: '13px',
      fontWeight: 500,
      marginBottom: '2px',
      margin: '0 0 2px',
      transition: 'color 0.3s',
    },
    featureDesc: {
      fontSize: '12px',
      color: 'rgba(255,255,255,0.3)',
      lineHeight: 1.5,
      margin: 0,
    },
    testimonial: {
      display: 'flex',
      alignItems: 'center',
      gap: '12px',
      paddingTop: '20px',
      borderTop: '1px solid rgba(255,255,255,0.07)',
    },
    testimonialAv: {
      width: '26px',
      height: '26px',
      borderRadius: '50%',
    },
    testimonialText: {
      fontSize: '13px',
      color: 'rgba(255,255,255,0.4)',
      lineHeight: 1.5,
      margin: 0,
    },
  
    right: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '40px 32px',
    },
    card: {
      width: '100%',
      maxWidth: '400px',
    },
    cardTitle: {
      fontSize: '26px',
      fontWeight: 700,
      letterSpacing: '-0.02em',
      color: '#fff',
      marginBottom: '6px',
    },
    cardSub: {
      fontSize: '14px',
      color: 'rgba(255,255,255,0.4)',
      margin: 0,
    },
    linkBlue: {
      color: '#3b82f6',
      textDecoration: 'none',
      fontWeight: 500,
    },
    label: {
      fontSize: '13px',
      fontWeight: 500,
      color: 'rgba(255,255,255,0.7)',
    },
    hint: {
      fontSize: '11px',
      color: 'rgba(255,255,255,0.25)',
      margin: 0,
    },
    input: {
      flex: 1,
      background: 'transparent',
      border: 'none',
      outline: 'none',
      color: 'rgba(255,255,255,0.85)',
      fontSize: '14px',
      fontFamily: 'inherit',
      caretColor: '#3b82f6',
    },
    submitBtn: {
      height: '44px',
      borderRadius: '10px',
      background: 'rgba(255,255,255,0.08)',
      border: '1px solid rgba(255,255,255,0.18)',
      color: '#fff',
      fontSize: '14px',
      fontWeight: 600,
      cursor: 'pointer',
      transition: 'background 0.15s, transform 0.15s, opacity 0.15s',
      letterSpacing: '-0.01em',
    },
    spinner: {
      width: '14px',
      height: '14px',
      border: '2px solid rgba(255,255,255,0.2)',
      borderTop: '2px solid #fff',
      borderRadius: '50%',
      animation: 'spin 0.7s linear infinite',
      display: 'inline-block',
    },
    divider: {
      display: 'flex',
      alignItems: 'center',
      gap: '12px',
      margin: '22px 0',
    },
    dividerLine: {
      flex: 1,
      height: '1px',
      background: 'rgba(255,255,255,0.08)',
    },
    dividerText: {
      fontSize: '12px',
      color: 'rgba(255,255,255,0.3)',
      whiteSpace: 'nowrap',
    },
    githubBtn: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '10px',
      width: '100%',
      height: '44px',
      borderRadius: '10px',
      background: 'rgba(255,255,255,0.04)',
      border: '1px solid rgba(255,255,255,0.12)',
      color: 'rgba(255,255,255,0.75)',
      fontSize: '14px',
      fontWeight: 500,
      cursor: 'pointer',
      transition: 'background 0.15s',
    },
    fine: {
      marginTop: '20px',
      fontSize: '12px',
      color: 'rgba(255,255,255,0.25)',
      textAlign: 'center',
      lineHeight: 1.6,
    },
    fineLink: {
      color: 'rgba(255,255,255,0.45)',
      textDecoration: 'underline',
      textDecorationColor: 'rgba(255,255,255,0.2)',
    },
  };